# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.programTitle = QtWidgets.QLabel(Form)
        self.programTitle.setGeometry(QtCore.QRect(250, 0, 506, 57))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programTitle.sizePolicy().hasHeightForWidth())
        self.programTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.programTitle.setFont(font)
        self.programTitle.setObjectName("programTitle")
        self.learning_combo = QtWidgets.QComboBox(Form)
        self.learning_combo.setGeometry(QtCore.QRect(530, 110, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.learning_combo.setFont(font)
        self.learning_combo.setObjectName("learning_combo")
        self.learning_combo.addItem("")
        self.learning_combo.addItem("")
        self.selectFolder_radio = QtWidgets.QRadioButton(Form)
        self.selectFolder_radio.setGeometry(QtCore.QRect(50, 80, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectFolder_radio.setFont(font)
        self.selectFolder_radio.setObjectName("selectFolder_radio")
        self.selectCSV_radio = QtWidgets.QRadioButton(Form)
        self.selectCSV_radio.setGeometry(QtCore.QRect(50, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectCSV_radio.setFont(font)
        self.selectCSV_radio.setObjectName("selectCSV_radio")
        self.selectFolder_edit = QtWidgets.QLineEdit(Form)
        self.selectFolder_edit.setGeometry(QtCore.QRect(230, 80, 191, 20))
        self.selectFolder_edit.setObjectName("selectFolder_edit")
        self.selectCSV_edit = QtWidgets.QLineEdit(Form)
        self.selectCSV_edit.setGeometry(QtCore.QRect(230, 110, 191, 20))
        self.selectCSV_edit.setObjectName("selectCSV_edit")
        self.selectFolder_browser = QtWidgets.QPushButton(Form)
        self.selectFolder_browser.setGeometry(QtCore.QRect(430, 80, 75, 23))
        self.selectFolder_browser.setObjectName("selectFolder_browser")
        self.selectCSV_browser = QtWidgets.QPushButton(Form)
        self.selectCSV_browser.setGeometry(QtCore.QRect(430, 110, 75, 23))
        self.selectCSV_browser.setObjectName("selectCSV_browser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(550, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(640, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(720, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(650, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(350, 200, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.colorspace_combo = QtWidgets.QComboBox(Form)
        self.colorspace_combo.setGeometry(QtCore.QRect(710, 110, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorspace_combo.setFont(font)
        self.colorspace_combo.setObjectName("colorspace_combo")
        self.colorspace_combo.addItem("")
        self.colorspace_combo.addItem("")
        self.colorspace_combo.addItem("")
        self.selectK_edit = QtWidgets.QLineEdit(Form)
        self.selectK_edit.setGeometry(QtCore.QRect(650, 110, 41, 20))
        self.selectK_edit.setObjectName("selectK_edit")
        self.startTrain_button = QtWidgets.QPushButton(Form)
        self.startTrain_button.setGeometry(QtCore.QRect(820, 80, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.startTrain_button.setFont(font)
        self.startTrain_button.setObjectName("startTrain_button")
        self.inputImage_label = QtWidgets.QLabel(Form)
        self.inputImage_label.setGeometry(QtCore.QRect(50, 190, 200, 200))
        self.inputImage_label.setMinimumSize(QtCore.QSize(200, 200))
        self.inputImage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImage_label.setObjectName("inputImage_label")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(90, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.selectImage_button = QtWidgets.QPushButton(Form)
        self.selectImage_button.setGeometry(QtCore.QRect(50, 410, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.selectImage_button.setFont(font)
        self.selectImage_button.setObjectName("selectImage_button")
        self.accuracy_label = QtWidgets.QLabel(Form)
        self.accuracy_label.setGeometry(QtCore.QRect(640, 240, 100, 100))
        self.accuracy_label.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.accuracy_label.setFont(font)
        self.accuracy_label.setText("")
        self.accuracy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.accuracy_label.setObjectName("accuracy_label")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(300, 290, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.originalClass_label = QtWidgets.QLabel(Form)
        self.originalClass_label.setGeometry(QtCore.QRect(450, 200, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.originalClass_label.setFont(font)
        self.originalClass_label.setObjectName("originalClass_label")
        self.predictedClass_label = QtWidgets.QLabel(Form)
        self.predictedClass_label.setGeometry(QtCore.QRect(450, 290, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predictedClass_label.setFont(font)
        self.predictedClass_label.setObjectName("predictedClass_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Analisis Sentimen"))
        self.programTitle.setText(_translate("Form", "Jajal"))
        self.learning_combo.setItemText(0, _translate("Form", "Naive Bayes"))
        self.learning_combo.setItemText(1, _translate("Form", "k-NN"))
        self.selectFolder_radio.setText(_translate("Form", "Select Image Folder"))
        self.selectCSV_radio.setText(_translate("Form", "Select Image CSV"))
        self.selectFolder_browser.setText(_translate("Form", "Browse"))
        self.selectCSV_browser.setText(_translate("Form", "Browse"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Metode:</p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">k:</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">Colorspace:</p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">Akurasi:</p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\">Kelas asli:</p></body></html>"))
        self.colorspace_combo.setItemText(0, _translate("Form", "Grayscale"))
        self.colorspace_combo.setItemText(1, _translate("Form", "HSV"))
        self.colorspace_combo.setItemText(2, _translate("Form", "RGB"))
        self.startTrain_button.setText(_translate("Form", "START TRAINING"))
        self.inputImage_label.setText(_translate("Form", "Masukkan Gambar"))
        self.label_7.setText(_translate("Form", "Input Image"))
        self.selectImage_button.setText(_translate("Form", "SELECT IMAGE"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\">Kelas terprediksi:</p></body></html>"))
        self.originalClass_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.predictedClass_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))

